# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        -   --ignore=E501,E402,W504,W503
        -   --in-place
        language_version: python3.7
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3.7
    -   id: flake8
        args:
        -   --ignore=E501,E402,W504,W503
        -   --jobs=1
        language_version: python3.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.1.4
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.700
    hooks:
    -   id: mypy
-   repo: https://github.com/miki725/importanize/
    rev: 'master'
    hooks:
    -   id: importanize
        args: [--verbose]
